# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shQQOeGXQ5u7TMJ_0JqiSRgAkric-yM_
"""

# RNATPH Package Initializer
import model
import ut
import modules