# -*- coding: utf-8 -*-
"""util.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shQQOeGXQ5u7TMJ_0JqiSRgAkric-yM_
"""

import numpy as np
import pandas as pd
import os

# RNATPH Utility Functions
def load_target(gene: str, df_Sp: pd.DataFrame, df_Un: pd.DataFrame, n_replicates: int) -> tuple:
    assert type(n_replicates) == int, "n_replicates must be an integer."
    Sp_star = df_Sp.loc[gene].to_numpy(dtype=np.float64).reshape(n_replicates, -1).T
    Un_star = df_Un.loc[gene].to_numpy(dtype=np.float64).reshape(n_replicates, -1).T
    return Sp_star, Un_star

def load_observation_period(experimental_timepoints_list: list):
    t_star = np.array(experimental_timepoints_list, dtype=np.float64).reshape(-1,1)
    end_min = int(np.max(t_star))
    start_min = int(np.min(t_star))
    t_f = np.linspace(start_min, end_min, (end_min - start_min) + 1).reshape(-1,1)
    t_star /= 60
    t_f /= 60
    return t_star, t_f